#!/usr/bin/env python3
"""
Prefix statistics for the TZUR Original display wordlists.

For each wordlist this reports, by Unicode codepoint:
  - whether 4-character prefix uniqueness holds (all 2048 prefixes distinct)
  - the count of distinct 2-, 3-, and 4-character prefixes
  - the largest prefix-collision group at each length, with an example
  - the most common 2-, 3-, and 4-character prefixes

BIP-39's original 4-character-prefix property lets a wallet identify a word
from its first four letters for autocomplete. It is achievable for English and
most Latin-script lists but structurally infeasible for several scripts where
short word stems dominate. This script quantifies realized uniqueness per
language so implementers know exactly when prefix autocomplete is safe and when
they must fall back to full-word matching (BIP draft, Display wordlist
requirements SHOULD 1).

"Character" here means Unicode codepoint, not grapheme cluster. For scripts
that build syllables from combining sequences (Devanagari, Thai, Hangul jamo
in decomposed form) a codepoint prefix can split a grapheme; the figures are a
lower bound on what a grapheme-aware implementation would achieve, and are the
conservative number an implementer should plan against.

Run with no arguments to print the report to stdout. Pass --write to
regenerate docs/prefix-statistics.md in place.
"""

import sys
from collections import Counter
from pathlib import Path

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
TZUR_DIR = REPO_ROOT / "wordlists" / "tzur-original"
REPORT_PATH = REPO_ROOT / "docs" / "prefix-statistics.md"
EXPECTED_WORD_COUNT = 2048


def load_words(path: Path) -> list[str]:
    words = path.read_text(encoding="utf-8").strip().split("\n")
    if len(words) != EXPECTED_WORD_COUNT:
        raise RuntimeError(
            f"{path.name} has {len(words)} entries, expected {EXPECTED_WORD_COUNT}"
        )
    return words


def prefix_stats(words: list[str], n: int):
    """Return (distinct_count, largest_group_size, largest_group_prefix,
    largest_group_examples) for n-character prefixes."""
    counts = Counter(w[:n] for w in words)
    distinct = len(counts)
    prefix, group_size = counts.most_common(1)[0]
    examples = [w for w in words if w[:n] == prefix][:4]
    return distinct, group_size, prefix, examples


def analyze(lang: str, words: list[str]) -> dict:
    p2 = prefix_stats(words, 2)
    p3 = prefix_stats(words, 3)
    p4 = prefix_stats(words, 4)
    top2 = Counter(w[:2] for w in words).most_common(5)
    top3 = Counter(w[:3] for w in words).most_common(5)
    top4 = Counter(w[:4] for w in words).most_common(5)
    return {
        "lang": lang,
        "p2": p2, "p3": p3, "p4": p4,
        "top2": top2, "top3": top3, "top4": top4,
        "unique4": p4[0] == EXPECTED_WORD_COUNT,
    }


def build_report(results: list[dict]) -> str:
    lines = []
    lines.append("# Prefix statistics (TZUR Original display wordlists)")
    lines.append("")
    lines.append(
        "Generated by [`validation/prefix_stats.py`](../validation/prefix_stats.py). "
        "Regenerate with `python validation/prefix_stats.py --write`."
    )
    lines.append("")
    lines.append(
        "BIP-39's original 4-character-prefix property lets a wallet identify a word "
        "from its first four letters, which is what makes prefix autocomplete possible. "
        "It is achievable for English and most Latin-script lists but structurally "
        "infeasible for several scripts where short word stems dominate. The BIP draft "
        "(Display wordlist requirements SHOULD 1) treats 4-character prefix uniqueness "
        "as a SHOULD, not a MUST, and instructs wallets relying on prefix autocomplete "
        "to fall back to full-word matching wherever uniqueness is below 2048/2048. "
        "This report quantifies realized uniqueness per language so implementers know "
        "exactly when that fallback is required."
    )
    lines.append("")
    lines.append(
        "**\"Character\" means Unicode codepoint, not grapheme cluster.** For scripts "
        "that build syllables from combining sequences a codepoint prefix can split a "
        "grapheme, so these figures are a conservative lower bound on what a "
        "grapheme-aware implementation would achieve. Plan against these numbers, not "
        "against a more optimistic grapheme count."
    )
    lines.append("")
    lines.append(
        "**Bottom line:** 4-character prefix uniqueness holds for only one language "
        "(Korean); two more (Chinese Simplified, Chinese Traditional) and Japanese "
        "miss it by a single collision. Every other list falls short, so a wallet that "
        "ships display wordlists MUST NOT assume 4-character prefixes are unique and "
        "MUST fall back to full-word matching. Use the per-language figures below to "
        "decide whether to offer prefix autocomplete at all in a given language."
    )
    lines.append("")

    # Summary table.
    lines.append("## Per-language summary")
    lines.append("")
    lines.append(
        "| Language | 4-char unique? | distinct 4-char | distinct 3-char | "
        "distinct 2-char | largest 4-char collision group |"
    )
    lines.append("|---|---|---:|---:|---:|---:|")
    for r in results:
        verdict = "**Yes (2048/2048)**" if r["unique4"] else "No"
        d4 = r["p4"][0]
        d3 = r["p3"][0]
        d2 = r["p2"][0]
        big = r["p4"][1]
        lines.append(
            f"| {r['lang']} | {verdict} | {d4} | {d3} | {d2} | {big} |"
        )
    lines.append("")
    lines.append(
        "\"distinct N-char\" is the number of distinct N-character prefixes across the "
        "2048 entries; 2048 means every entry has a unique N-character prefix. \"largest "
        "4-char collision group\" is the number of entries that share the single most "
        "common 4-character prefix (1 would mean fully unique)."
    )
    lines.append("")

    # Per-language detail.
    lines.append("## Per-language detail")
    lines.append("")
    for r in results:
        lines.append(f"### {r['lang']}")
        lines.append("")
        verdict = (
            "Yes, every entry has a unique 4-character prefix."
            if r["unique4"]
            else "No. Wallets must fall back to full-word matching for autocomplete."
        )
        lines.append(f"- 4-character prefix uniqueness: {verdict}")
        _, g4, pre4, ex4 = r["p4"]
        if g4 > 1:
            lines.append(
                f"- Largest 4-character collision group: {g4} entries share the prefix "
                f"`{pre4}` (e.g. {', '.join('`' + w + '`' for w in ex4)})."
            )
        else:
            lines.append("- Largest 4-character collision group: 1 (no collisions).")
        lines.append(
            "- Most common 2-character prefixes: "
            + ", ".join(f"`{p}` ({c})" for p, c in r["top2"])
        )
        lines.append(
            "- Most common 3-character prefixes: "
            + ", ".join(f"`{p}` ({c})" for p, c in r["top3"])
        )
        lines.append(
            "- Most common 4-character prefixes: "
            + ", ".join(f"`{p}` ({c})" for p, c in r["top4"])
        )
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    results = []
    for path in sorted(TZUR_DIR.glob("*.txt")):
        words = load_words(path)
        results.append(analyze(path.stem, words))

    report = build_report(results)

    if "--write" in sys.argv:
        REPORT_PATH.write_text(report, encoding="utf-8", newline="\n")
        print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)}")
    else:
        print(report)


if __name__ == "__main__":
    main()
